[package]
name = "tower"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]

[dependencies]
log = "*"
env_logger = "*"
rusqlite = "*"
hyper = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
clap = "*"
